export const CONST_TEXT = {
  APP_NAME: "Task Sharing",
  LOGIN: "ログイン",
  LOGOUT: "ログアウト",
  EMAIL: "メールアドレス",
  PASSWORD: "パスワード",
  TASK_LIST: "タスク一覧",
  TO_TASK_LIST: "タスク一覧へ",
  BACK_TO_LIST: "タスク一覧に戻る",
  TASK_DETAIL: "タスク詳細",
  CREATE_TASK: "タスク作成",
  NO_TASKS: "タスクがありません",
  ALL: "すべて",
  INCOMPLETE: "未完",
  COMPLETED: "完了",
  MARK_AS_COMPLETE: "完了にする",
  MARK_AS_INCOMPLETE: "未完にする",
  TITLE: "タイトル",
  CATEGORY: "カテゴリー",
  ASSIGNEE: "担当者",
  MEMO: "メモ",
  EDIT: "編集",
  CREATE: "作成",
  SAVE: "保存",
  CANCEL: "キャンセル",
  LOGIN_LOADING: "ログイン中...",
  LOADING: "読み込み中...",
  LOGIN_FAILED: "メールアドレスまたはパスワードが間違っています",
  REGISTER: "ユーザー登録",
  REGISTER_BUTTON: "登録",
  REGISTERING: "登録中...",
  ALREADY_HAVE_ACCOUNT: "既にアカウントをお持ちですか？",
  FREE_REGISTER: "新規登録",
  SHARE_TASK: "タスクを共有",
  ENTER_USER_ID: "ユーザーIDを入力して共有します",
  USER_ID_PLACEHOLDER: "ユーザーID (例: user@example.com)",
  SHARE: "共有する",
  SHARE_FAILED: "共有に失敗しました",
  SHARE_SUCCESS: "タスクを共有しました",
  DELETE_CONFIRM: "このタスクを削除してもよろしいですか？",
  DELETE: "削除",
  NETWORK_ERROR: "ネットワークエラーが発生しました",
  REGISTER_FAILED: "登録に失敗しました",
  NAME: "名前",
  PASSWORD_CONFIRM: "パスワード（確認）",
  TAGLINE: "シンプルなタスク管理アプリ",
  FEATURES_TITLE: "主な機能",
  FEATURE_1: "タスク管理 - タスクを作成・編集・削除し、完了状態を管理",
  FEATURE_2: "タスク共有 - メールアドレスでタスクを他のユーザーと共有",
  FEATURE_3: "ログイン認証 - メールアドレスとパスワードでログイン",
  TASK_CREATE_FAILED: "タスク作成に失敗しました",
  TASK_FETCH_FAILED: "タスクの取得に失敗しました",
  TASK_UPDATE_FAILED: "タスクの更新に失敗しました",
  TASK_DELETE_FAILED: "タスクの削除に失敗しました",
  MEMO_LABEL: "メモ：",
  EMAIL_PASSWORD_REQUIRED: "メールアドレスとパスワードが必要です",
  USER_NOT_FOUND: "ユーザーが見つかりません",
  PASSWORD_INCORRECT: "パスワードが正しくありません",
  EMAIL_NAME_PASSWORD_REQUIRED: "メールアドレス、名前、パスワードが必要です",
  PASSWORD_MISMATCH: "パスワードが一致しません",
  PASSWORD_MIN_LENGTH: "パスワードは6文字以上である必要があります",
  INVALID_EMAIL: "有効なメールアドレスを入力してください",
  REGISTER_SUCCESS: "ユーザーを登録しました",
  EMAIL_ALREADY_REGISTERED: "このメールアドレスは既に登録されています",
  REGISTER_ERROR: "ユーザー登録に失敗しました",
  SHARE_TARGET_NOT_FOUND: "共有対象のユーザーが見つかりません",
};
