export const CONST_TEXT = {
  APP_NAME: "Task Sharing",
  LOGIN: "ログイン",
  LOGOUT: "ログアウト",
  EMAIL: "メールアドレス",
  PASSWORD: "パスワード",
  TASK_LIST: "タスク一覧",
  TO_TASK_LIST: "タスク一覧へ",
  BACK_TO_LIST: "タスク一覧に戻る",
  TASK_DETAIL: "タスク詳細",
  CREATE_TASK: "タスク作成",
  NO_TASKS: "タスクがありません",
  ALL: "すべて",
  INCOMPLETE: "未完",
  COMPLETED: "完了",
  MARK_AS_COMPLETE: "完了にする",
  MARK_AS_INCOMPLETE: "未完にする",
  TITLE: "タイトル",
  CATEGORY: "カテゴリー",
  ASSIGNEE: "担当者",
  MEMO: "メモ",
  EDIT: "編集",
  CREATE: "作成",
  SAVE: "保存",
  CANCEL: "キャンセル",
};
